server:
  port: 9040
spring:
  application:
    name: txjava-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/XiaoGouXiong/config-file.git
          username: yushibom@qq.com
          password: q285459607
          #主目录下的文件路径
          search-paths: config-file
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka