server:
  port: 8082
spring:
  application:
    name: txjava-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.63.78:3306/yushibo
    username: eop
    password: mysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
feign:
  hystrix:
   enabled: true


txjava-order:
 ribbon:
  NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

