server:
  port: 9030
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
zuul:
  routes:
    txjava-user:
      path: /user/**
      serviceId: txjava-user
    txjava-order:
      path: /order/**
      serviceId: txjava-order
  PreFilter: #设置过滤器是否开启
   pre:
    disable: true
